import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../src/index.js';
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../migrations/0002_free_routes.sql',import.meta.url),'utf8'));const db={withSession(){return this;},prepare(text){const raw=sql.prepare(text);let args=[];return {bind(...v){args=v;return this;},async first(){return raw.get(...args)||null;},async all(){return {results:raw.all(...args)};},async run(){return {meta:{changes:Number(raw.run(...args).changes)}};}};}};const env={DB:db,CR_ADMIN_TOKEN:'a'.repeat(48),ASSETS:{fetch:()=>new Response('admin')}};const api=async(path,method='GET',data,token,headers={})=>{const r=await worker.fetch(new Request('https://unit.test'+path,{method,headers:{...headers,...(token?{Authorization:'Bearer '+token}:{})},body:data===undefined?undefined:JSON.stringify(data)}),env);return {status:r.status,data:await r.json()};};return {sql,api,env};}
const entry={name:'测试操场',route:{points:[{lat:30,lon:120},{lat:30.001,lon:120}],loops:0},motion:{mode:'smooth',speed:3,low:2,high:4}};
test('free health and public route access need no user account or license keys',async()=>{const {sql,api}=fixture();assert.equal((await api('/health')).data.free,true);assert.deepEqual((await api('/api/routes')).data,{entries:[]});for(const p of ['/api/auth/self-record','/api/orders','/api/device/register'])assert.equal((await api(p,'POST',{})).status,404);sql.close();});
test('admin authorization, publishing, update and deletion',async()=>{const {sql,api,env}=fixture();assert.equal((await api('/api/admin/routes','POST',entry)).status,401);assert.equal((await api('/api/admin/routes','POST',entry,'wrong')).status,403);const saved=await api('/api/admin/routes','POST',entry,env.CR_ADMIN_TOKEN);assert.equal(saved.status,200);assert.equal((await api('/api/routes')).data.entries[0].route.loops,0);const updated=await api('/api/admin/routes','POST',{...entry,id:saved.data.id,name:'修改名称'},env.CR_ADMIN_TOKEN);assert.equal(updated.status,200);assert.equal((await api('/api/routes')).data.entries[0].name,'修改名称');assert.equal((await api('/api/admin/routes/'+saved.data.id,'DELETE',undefined,env.CR_ADMIN_TOKEN)).status,200);assert.deepEqual((await api('/api/routes')).data.entries,[]);sql.close();});
test('invalid routes and cross-origin modification rejected',async()=>{const {sql,api,env}=fixture();assert.equal((await api('/api/admin/routes','POST',entry,env.CR_ADMIN_TOKEN,{Origin:'https://evil.test'})).status,403);for(const v of [{...entry,motion:{speed:21}},{...entry,route:{points:[{lat:30,lon:120},{lat:30,lon:120}]}},{...entry,route:{...entry.route,loops:.5}}])assert.equal((await api('/api/admin/routes','POST',v,env.CR_ADMIN_TOKEN)).status,400);sql.close();});
test('route cap atomic and existing entries remain editable',async()=>{const {sql,api,env}=fixture();for(let i=0;i<50;i++)assert.equal((await api('/api/admin/routes','POST',{...entry,id:'route-'+i},env.CR_ADMIN_TOKEN)).status,200);assert.equal((await api('/api/admin/routes','POST',{...entry,id:'extra'},env.CR_ADMIN_TOKEN)).status,400);assert.equal((await api('/api/admin/routes','POST',{...entry,id:'route-0',name:'更新'},env.CR_ADMIN_TOKEN)).status,200);assert.equal((await api('/api/routes')).data.entries.length,50);sql.close();});
